project_id = "ocrsfcjiutvojzdfotou"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.public-apply]
    verify_jwt = false
  [functions.generate-shortlist]
    verify_jwt = false
